# Generated by Django 6.0.6 on 2026-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UonClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uon_id', models.CharField(max_length=64, unique=True, verbose_name='ID в U-ON')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные из U-ON')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('uon_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создан в U-ON')),
            ],
            options={
                'verbose_name': 'клиент U-ON',
                'verbose_name_plural': 'клиенты U-ON',
                'ordering': ['-uon_created_at', '-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='UonDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uon_id', models.CharField(max_length=64, unique=True, verbose_name='ID в U-ON')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные из U-ON')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('status_name', models.CharField(blank=True, max_length=100, verbose_name='Статус в U-ON')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Менеджер в U-ON')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('request_uon_id', models.CharField(blank=True, max_length=64, verbose_name='ID заявки в U-ON')),
                ('uon_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создано в U-ON')),
            ],
            options={
                'verbose_name': 'обращение U-ON',
                'verbose_name_plural': 'обращения U-ON',
                'ordering': ['-uon_created_at', '-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='UonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uon_id', models.CharField(max_length=64, unique=True, verbose_name='ID в U-ON')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные из U-ON')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status_name', models.CharField(blank=True, max_length=100, verbose_name='Статус в U-ON')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Менеджер в U-ON')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('uon_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создана в U-ON')),
            ],
            options={
                'verbose_name': 'заявка U-ON',
                'verbose_name_plural': 'заявки U-ON',
                'ordering': ['-uon_created_at', '-synced_at'],
            },
        ),
    ]
