# Generated by Django 6.0.6 on 2026-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_uonrequestrecord_uonwebhooklog_delete_uondeal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UonLeadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uon_id', models.CharField(max_length=64, unique=True, verbose_name='ID в U-ON')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные из U-ON')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('client_id', models.CharField(blank=True, max_length=64, verbose_name='ID клиента в U-ON')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status_id', models.CharField(blank=True, max_length=20, verbose_name='ID статуса в U-ON')),
                ('status_name', models.CharField(blank=True, max_length=100, verbose_name='Статус в U-ON')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Менеджер в U-ON')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_archive', models.BooleanField(default=False, verbose_name='В архиве')),
                ('uon_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создано в U-ON')),
            ],
            options={
                'verbose_name': 'обращение U-ON',
                'verbose_name_plural': 'обращения U-ON',
                'ordering': ['-uon_created_at', '-synced_at'],
            },
        ),
    ]
