# Generated by Django 6.0.6 on 2026-07-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_uonleadrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='uonclient',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='inn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='is_main_contact',
            field=models.BooleanField(default=False, help_text='True — это тот, кто оформлял заявку (client_id заявки); False — сопутствующий турист.', verbose_name='Основной заказчик'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя (лат.)'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Паспорт (дата выдачи)'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Паспорт (кем выдан)'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Паспорт (номер)'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='phone_home',
            field=models.CharField(blank=True, max_length=32, verbose_name='Доп. телефон'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='sex',
            field=models.CharField(blank=True, max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='social_vk',
            field=models.CharField(blank=True, max_length=255, verbose_name='ВКонтакте'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='surname_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия (лат.)'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='viber',
            field=models.CharField(blank=True, max_length=32, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='zagran_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Загранпаспорт (действителен до)'),
        ),
        migrations.AddField(
            model_name='uonclient',
            name='zagran_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Загранпаспорт (номер)'),
        ),
    ]
