# Generated by Django 6.0.6 on 2026-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_uonfollowupchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='uonrequestrecord',
            name='date_begin',
            field=models.DateField(blank=True, help_text='date_begin из сырых данных заявки — используется для напоминания «выдать документы» за 5 дней.', null=True, verbose_name='Дата вылета'),
        ),
        migrations.AddField(
            model_name='uonrequestrecord',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания тура'),
        ),
    ]
