# Generated by Django 6.0.6 on 2026-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Главный экран (hero)')),
                ('why_us_solo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='«Индивидуальный подбор»')),
                ('why_us_family', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='«Семейный отдых»')),
                ('why_us_cruise', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='«Круизы»')),
                ('why_us_excursion', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='«Экскурсионные туры»')),
                ('why_us_support', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='«Поддержка без стресса»')),
                ('office_photo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фото офиса')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'изображения сайта',
                'verbose_name_plural': 'изображения сайта',
            },
        ),
    ]
