# Generated by Django 6.0.6 on 2026-09-02 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_certificate_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='Скан/фото сертификата (изображение или PDF)'),
        ),
    ]
