# Generated by Django 6.0.6 on 2026-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_seed_default_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uon_reminder_id',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при синхронизации напоминаний из U-ON — не редактировать вручную.', max_length=64, null=True, unique=True, verbose_name='ID напоминания U-ON'),
        ),
    ]
