# Generated by Django 6.0.6 on 2026-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_task_uon_reminder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='При переносе в последнюю колонку доски автоматически создаётся копия на завтра.', verbose_name='Ежедневная (повторяющаяся)'),
        ),
    ]
