# Generated by Django 6.0.6 on 2026-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_task_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uon_record_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID записи U-ON'),
        ),
        migrations.AddField(
            model_name='task',
            name='uon_record_kind',
            field=models.CharField(blank=True, choices=[('request', 'Заявка'), ('lead', 'Обращение')], help_text='К какой сущности U-ON относится задача — для ссылки «Открыть в U-ON».', max_length=10, verbose_name='Тип записи U-ON'),
        ),
    ]
