# Generated by Django 6.0.6 on 2026-09-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_task_uon_record_id_task_uon_record_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('postponed', 'Отложено'), ('done', 'Выполнено'), ('cancelled', 'Отменено')], default='new', help_text='Независим от колонки доски — просто рабочая пометка исполнителя. При переводе в «Отложено» дедлайн автоматически сдвигается на +3 дня (см. TaskUpdateSerializer.update).', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
