# Generated by Django 6.0.6 on 2026-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='preferred_contact_channel',
            field=models.CharField(blank=True, choices=[('phone', 'Телефон'), ('email', 'e-mail'), ('max', 'MAX'), ('telegram', 'Telegram'), ('whatsapp', 'Whatsapp'), ('vk', 'VK')], max_length=20, verbose_name='Приоритетный канал связи'),
        ),
    ]
