# Generated by Django 6.0.6 on 2026-09-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='id')),
                ('network', models.CharField(max_length=255, verbose_name='Сеть / ТО')),
                ('kind', models.CharField(blank=True, max_length=50, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'плюшки для агентов (ЮВА)',
                'verbose_name_plural': 'плюшки для агентов (ЮВА)',
                'ordering': ['order', 'network'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'контакт (ЮВА)',
                'verbose_name_plural': 'контакты (ЮВА)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные (без направлений)')),
            ],
            options={
                'verbose_name': 'страна (ЮВА)',
                'verbose_name_plural': 'страны (ЮВА)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('region', models.JSONField(blank=True, default=dict, verbose_name='region')),
            ],
            options={
                'verbose_name': 'регион ЮВА (общие данные)',
                'verbose_name_plural': 'регион ЮВА (общие данные)',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='seakb.country')),
            ],
            options={
                'verbose_name': 'направление (ЮВА)',
                'verbose_name_plural': 'направления (ЮВА)',
                'ordering': ['country__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Бренд')),
                ('stars', models.FloatField(blank=True, null=True, verbose_name='Звёзды')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('detail_level', models.CharField(blank=True, max_length=20, verbose_name='Детализация')),
                ('agent_perks_id', models.CharField(blank=True, max_length=100, verbose_name='Группа плюшек (id)')),
                ('for_whom', models.JSONField(blank=True, default=list, verbose_name='Для кого')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('contacts', models.ManyToManyField(blank=True, related_name='hotels', to='seakb.contact')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='seakb.country')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='seakb.destination')),
            ],
            options={
                'verbose_name': 'отель (ЮВА)',
                'verbose_name_plural': 'отели (ЮВА)',
                'ordering': ['country__order', 'destination__order', 'name'],
            },
        ),
    ]
