# Generated by Django 6.0.6 on 2026-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Растёт при каждом открытии страницы статьи на сайте (ArticleDetailView) — без дедупликации по IP/сессии, простой счётчик (ТЗ по требованию клиента, 03.09.2026).', verbose_name='Просмотров'),
        ),
    ]
