# Generated by Django 6.0.6 on 2026-07-05 14:36

import django.db.models.deletion
import telegrambot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('event_type', models.CharField(choices=[('task_assigned', 'Назначена задача'), ('lead_assigned', 'Назначена заявка')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.CharField(default=telegrambot.models.generate_link_code, editable=False, max_length=32, unique=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID чата в Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='Username в Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
