# Generated by Django 6.0.6 on 2026-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramnotificationlog',
            name='event_type',
            field=models.CharField(choices=[('task_assigned', 'Назначена задача'), ('lead_assigned', 'Назначена заявка'), ('plan_digest', 'Сводка по плану')], max_length=30),
        ),
    ]
