# Generated by Django 6.0.6 on 2026-08-26 07:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_monthlyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000'), max_digits=10, verbose_name='Оклад'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Выставляется вручную по итогам месяца — 3% при выполненном SLA и не более 2 пропусков ежедневных задач, 1% при более серьёзных нарушениях, 0% при грубом нарушении.', max_digits=5, verbose_name='% от комиссии остальных (SLA/ежедневные задачи)'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='% от своей комиссии'),
        ),
    ]
