# Generated by Django 6.0.6 on 2026-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_monthlyplan_base_salary_monthlyplan_bonus_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='uon_request_id',
            field=models.CharField(blank=True, help_text='Заполняется при переводе обращения в заявку (POST /request/create.json) — отдельная сущность и ID-последовательность от uon_ticket_id.', max_length=64, verbose_name='ID заявки U-ON'),
        ),
    ]
