# Generated by Django 6.0.6 on 2026-09-06 10:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_uon_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyplan',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='По умолчанию 3% — SLA считается выполненным, если руководитель явно не указал иное. Понижается вручную по итогам месяца: 1% при более серьёзных нарушениях, 0% при грубом нарушении (решение заказчика, 06.09.2026 — раньше по умолчанию было 0%, из-за чего бонус нужно было включать вручную каждый месяц, а не выключать при нарушении).', max_digits=5, verbose_name='% от комиссии остальных (SLA/ежедневные задачи)'),
        ),
    ]
