# Generated by Django 6.0.6 on 2026-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_workshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название уровня')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, unique=True, verbose_name='Порог (своя комиссия за месяц)')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% от своей комиссии на этом уровне')),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='target_commission',
        ),
    ]
