# Generated by Django 6.0.6 on 2026-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_seed_commission_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('options_proposed', 'Предложены варианты'), ('booked', 'Бронь'), ('prepaid', 'Внесена предоплата'), ('paid', 'Оплачено'), ('closed_won', 'Закрыта (успех)'), ('closed_lost', 'Закрыта (отказ)')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('options_proposed', 'Предложены варианты'), ('booked', 'Бронь'), ('prepaid', 'Внесена предоплата'), ('paid', 'Оплачено'), ('closed_won', 'Закрыта (успех)'), ('closed_lost', 'Закрыта (отказ)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('options_proposed', 'Предложены варианты'), ('booked', 'Бронь'), ('prepaid', 'Внесена предоплата'), ('paid', 'Оплачено'), ('closed_won', 'Закрыта (успех)'), ('closed_lost', 'Закрыта (отказ)')], max_length=20),
        ),
    ]
